Repository luunguyenthanhvu/ProjectAnToanThongTin, pull requests merged in 2024-12, with the labels that each got.

#6 add sign key tool project
  cipher-tools-rework/.gitignore
  cipher-tools-rework/.idea/.gitignore
  cipher-tools-rework/.idea/compiler.xml
  cipher-tools-rework/.idea/encodings.xml
  cipher-tools-rework/.idea/jarRepositories.xml
  cipher-tools-rework/.idea/libraries/flatlaf_3_5_2.xml
  cipher-tools-rework/.idea/misc.xml
  cipher-tools-rework/.idea/modules.xml
  cipher-tools-rework/.idea/vcs.xml
  cipher-tools-rework/myapp.iml
  cipher-tools-rework/src/Controller/AController.java
  cipher-tools-rework/src/Controller/SignatureScreen_Controller.java
  cipher-tools-rework/src/META-INF/MANIFEST.MF
  cipher-tools-rework/src/Main/App.java
  cipher-tools-rework/src/Model/Algorithm/Asymmetric/AsymmetricAlgorithm.java
  cipher-tools-rework/src/Model/Algorithm/Hash/HashAlgorithm.java
  cipher-tools-rework/src/Model/Screen/ModelObservable.java
  cipher-tools-rework/src/Model/Screen/ScreenObserver.java
  cipher-tools-rework/src/Model/Screen/SignatureScreen_Model.java
  cipher-tools-rework/src/MyException/ErrorType.java
  cipher-tools-rework/src/MyException/GlobalExceptionHandler.java
  cipher-tools-rework/src/MyException/MyAppException.java
  cipher-tools-rework/src/Util/MyUtil.java
  cipher-tools-rework/src/View/AScreenView.java
  cipher-tools-rework/src/View/SignatureScreen_View.java
  cipher-tools-rework/src/flatlaf-3.5.2.jar
Labels: new

#7 Add download tool and private key endpoints.
  TemplateProject/.gitignore
  TemplateProject/.idea/.gitignore
  TemplateProject/.idea/encodings.xml
  TemplateProject/.idea/misc.xml
  TemplateProject/.idea/vcs.xml
  TemplateProject/cipher-tool.exe
  TemplateProject/pom.xml
  TemplateProject/src/main/com/nlu/app/controller/DownloadController.java
  TemplateProject/src/main/webapp/WEB-INF/web.xml
  TemplateProject/src/main/webapp/index.jsp
Labels: new

#13 fix bug when load .pem key 🐧
  cipher-tools-rework/.idea/compiler.xml
  cipher-tools-rework/.idea/encodings.xml
  cipher-tools-rework/.idea/jarRepositories.xml
  cipher-tools-rework/.idea/libraries/myapp.xml
  cipher-tools-rework/.idea/misc.xml
  cipher-tools-rework/.idea/modules.xml
  cipher-tools-rework/.idea/workspace.xml
  cipher-tools-rework/cipher-tools-rework.iml
  cipher-tools-rework/src/Controller/SignatureScreen_Controller.java
  cipher-tools-rework/src/View/SignatureScreen_View.java
Labels: new, vu-ngu, ko-review=gay, my-grandma-run-faster-than-your-code

#14 Vu branch/admin checkout
  WebBanTraiCay/.idea/webContexts.xml
  WebBanTraiCay/src/main/java/nhom55/hcmuaf/services/BillService.java
  WebBanTraiCay/src/main/java/nhom55/hcmuaf/services/RegisterService.java
  WebBanTraiCay/src/main/webapp/WEB-INF/admin/order-list.jsp
  WebBanTraiCay/src/main/webapp/WEB-INF/admin/update-order.jsp
  WebBanTraiCay/src/main/webapp/static/images/icons8-certificate-50.png
  WebBanTraiCay/src/main/webapp/static/js/admin-js/updateOrder.js
  WebBanTraiCay/src/main/webapp/static/js/admin-js/updateOrder.js~
Labels: new, ko-review=gay

#15 add cipher tool executable file
  cipher-tools-rework/.idea/artifacts/cipher_tools_rework_jar.xml
  cipher-tools-rework/cipher-tool.exe
Labels: new
